# server configuration (optional)
# server:
#   port: 8081

spring:
  application:
    name: USER-SERVICE
  

management:
  health:
    circuitbreaker:
      enabled: true  # Enable circuit breaker health indicator
  endpoints:
    web:
      exposure:
        include: health  # Expose /actuator/health endpoint
  endpoint:
    health:
      show-details: always  # Always show health details

resilience4j:

  # -------------------------
  # CIRCUIT BREAKER CONFIG
  # -------------------------
  circuitbreaker:
    instances:
      ratingBroker:  # Unique name for this circuit breaker (used in @CircuitBreaker annotation)
        registerHealthIndicator: true
        slidingWindowSize: 5  # Number of recent calls to consider
        minimumNumberOfCalls: 5  # Minimum calls before CB calculates failure rate
        failureRateThreshold: 50  # If 50% of calls fail, CB opens
        waitDurationInOpenState: 6s  # Time CB stays open before transitioning to half-open
        permittedNumberOfCallsInHalfOpenState: 3  # Calls allowed in half-open state
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Auto transition without waiting for user trigger
        slidingWindowType: COUNT_BASED  # Count-based sliding window

  # -------------------------
  # RETRY CONFIG
  # -------------------------
  retry:
    instances:
      ratingRetry:  # Name of this retry config (used in @Retry annotation)
        max-attempts: 3  # Number of retry attempts
        wait-duration: 2s  # Wait time between each retry attempt

  # -------------------------
  # RATE LIMITER CONFIG
  # -------------------------
  ratelimiter:
    instances:
      userRateLimiter:  # Name of this rate limiter (used in @RateLimiter annotation)
        limitRefreshPeriod: 4s  # Time window to allow a fixed number of calls
        limitForPeriod: 2  # Max 2 calls per 4 seconds
        timeoutDuration: 0s  # Wait time to acquire permission (0 = no wait)
